### ISSUE TITLE
Error Running the clone : import org.cesiumjs.cs error

### ISSUE THREAD

**Issue by regita96** [iSergio/gwt-cs#14]
I am newbie for this development. i try to clone this code on eclipse and using Tomcat sever. 
However error is everywhere in the project that i believe because it can't handle Import org.cesiumjs.cs.*
Can you help me ?
Thank you

**Comment by iSergio** [comment]
Hello
I don't use Eclipse ) But...
You try open all project into Eclipse ? Or create a new project and use cesiumjs4gwt ?
If you open all project in Eclipse just do File->Import (and import as maven project).
If you create new project uses a cesiumjs4gwt do mvn clean install and then:
Created GWT project and then add inherit module in you GWT project file (*.gwt.xml)

`<inherits name="org.cesiumjs.Cesium"/>`

For example see showcase app. There are Showcase.gwt.xml in src/main/java/org/cleanlogic/cesiumjs4gwt and two files of html (Showcase.html and ShowcaseSuperDevMode.html) in last of them manual inject of CesiumJS framework for debugging.

**Comment by regita96** [comment]
Hello, Thanks for the answer. 
Now there is no error, whether opening cesiumjs4gwt or use this project on my own project.
However, i tried to run exactly one of your class example code, and i am not quite sure how call this class in my project.
I called showcaseBuilder.buildShowcase(); in the class implementing Entrypoint, but when i run in my tomcat, the link shows nothing. I am very new to the Cesium and GWT.
Is there any link to learn how to create new project using your cesiumjs4gwt ?
