### ISSUE TITLE
Property Name Spelling

### ISSUE THREAD

**Issue by weatherdrew** [iSergio/gwt-cs#2]
Greetings:

It appears that `MaterialProperty org.cesiumjs.cs.datasources.graphics.EllipseGraphics.materia` has been spelled incorrectly ("**materia**"), and is missing the **"l"** letter at the end of the JSProperty name.

Thank you for your work on this library, I enjoy using it.

**Comment by iSergio** [comment]
Thanks. Fixed.
Thank you for use the library.
