### ISSUE TITLE
Script injector

### ISSUE THREAD

**Issue by ibaca** [iSergio/gwt-cs#3]
Hi! awesome project, just one question I see you have created your own linker and you use "script" tags in modules that don't work in the xsiframe linker. Why don't you use the ClientBundle technique? (https://github.com/mstahv/g-leaflet/blob/master/src/main/java/org/peimari/gleaflet/client/resources/LeafletClientBundle.java)

**Comment by iSergio** [comment]
Hi!
So historically =)
You talk about GWT SuperDevMode ?
In this mode, i inject scripts in html file use CesiumNoScript.gwt.xml. In production i use Cesium.gwt.xml without any scripts in html file.
If serious:
1. With linker not need EntryPoint class for manual inject JS to code.
2. With linker i'm inject pre use code (Fix for SmartGWT)
3. All works out the box)

With ClientBundle i find problems with release widget.css(minified) and maybe will be problems with minified Cesium.js. But i'll try add support ClientBundle technique in the feature.
