### ISSUE TITLE
Cesium 1.42 Released

### ISSUE THREAD

**Issue by weatherdrew** [iSergio/gwt-cs#5]
Hi Sergio!

Can we get a recompile with the latest Cesium 1.42? They have added some nice new performance enhancements and other features:

https://cesium.com/blog/2018/02/01/cesium-version-1.42-released/

Cheers!

**Comment by iSergio** [comment]
Hi. I work under this release, i commit updates, but now i check all, and try add JUnit test. Release will be ready tomorrow or after tomorrow

**Comment by weatherdrew** [comment]
Thank you very much, you are the best!
