### ISSUE TITLE
ProviderViewModel support for custom BaseLayerPicker

### ISSUE THREAD

**Issue by Oraza1704** [iSergio/gwt-cs#6]
Hello.  I know not all Cesium capabilities are covered 100% but there is one in particular at the moment that I am interested in knowing the timeline for.  Do you know when you will be filling out the ProviderViewModel class?  Or do you have an example of filling out the baselayerpicker with custom imagery layers without using that class?  Thank you in advance.

**Comment by iSergio** [comment]
I’m glad what you choosing my framework) By your request i done ProviderViewModel and BaseLayerPicker widget. You can see example code: https://github.com/iSergio/gwt-cs/blob/master/gwt-cs-showcase/src/main/java/org/cleanlogic/showcase/client/examples/CustomBaseLayerPicker.java
Worked example: http://sergeserver.noip.me/gwt-cs-showcase/?example=Custom%20BaseLayerPicker%20widget

I hope this is what you wanted
