### ISSUE TITLE
Entity position as CallbackProperty

### ISSUE THREAD

**Issue by Oraza1704** [iSergio/gwt-cs#9]
Hello,

Although the Cesium docs show an Entity's position as a PositionProperty, it allows setting the position via a CallbackProperty.  For a simple example, I took the following showcase:

https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Billboards.html&label=Showcases

and added a new function: 

```javascript
var lat = 0.1;
function getPosition() {
   lat = lat + 0.1;
    if (lat >= 90) {
       lat = 0.1;
    }
    return Cesium.Cartesian3.fromDegrees(-75.6, lat);
} 
```

and replaced the billboard position with 

```
position : new Cesium.CallbackProperty(getPosition, false),
```

The billboard position will then update each frame.  I do not see a way within the framework to use a CallbackProperty for an entity's position.

I would be happy to work this issue, but wanted to make sure I was not missing something first.

**Comment by iSergio** [comment]
Hello, 
When i write wrapper, i don't find any documentation on use CallbackProperty with position of Entity. And in this moment i not find this in documentation. JavaScript not typed language, and in this problems. If you can give me link on documentation, i'll be happy.
CallbackProperty defined usage only examples (Callback Property example). By this example, i add positionPropery to EntityOptions and write example for CallbackPropery.
Example: https://sergeserver.noip.me/gwt-cs-showcase/?example=Callback%20Property

I hope this is what you wanted

**Comment by Oraza1704** [comment]
The positionProperty you added as a CallbackProperty is exactly what I was looking for.  Thank you!  I'll go ahead and close out this issue.
